### BASICS

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 2000

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[âœ](bold green)"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[sudo]
style = "bold red"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-8"
time_range = "10:00:00-14:00:00"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)@"
disabled = false
show_always = true

### APP-SPECIFIC

[crystal]
#format = "via [âœ¨ $version](bold blue) "

[dart]
#format = "via [ğŸ”° $version](bold red) "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[elm]
#format = "via [î˜¬ $version](cyan bold) "

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨â‡¡${count}"
behind = "ğŸ˜°â‡£${count}"
diverged = "ğŸ˜µâ‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "âœ“"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[golang]
#format = "via [ğŸğŸ’¨ $version](bold cyan) "

[java]
format = "via [â˜• $version](bold #8c6f38) "

[lua]
format = "via [ğŸŒ• $version](bold blue) "

[nodejs]
format = "via [ğŸ¤– $version](bold green) "

[php]
#format = "via [ğŸ”¹ $version](147 bold) "

[python]
symbol = "ğŸ‘¾ "
pyenv_version_name = true

[ruby]
#symbol = "ğŸ”º "

[rust]
format = "via [âš™ï¸ $version](red bold)"

[swift]
format = "via [ğŸ  $version](red bold)"
